- hosts: localhost
  connection: local
  gather_facts: no

  vars:
    homebrew_packages:
      - name: tmux
      - name: hub
      - name: ruby-build
      - name: openssl
      - name: readline
      - name: imagemagick
      - name: docker
      - name: docker-compose
      - name: tree
      - name: starship
      - name: peco
      - name: ghq
      - name: jq
      - name: starship
      - name: bat
      - name: fontforge
      - name: watch
      - name: direnv
      - name: anyenv
      - name: trash
      - name: pure
      - name: nvim
      - name: gnu-sed
        options: "--with-default-names"
  tasks:
    - name: homebrew update
      homebrew:
        update_homebrew: yes

    - name: homebrew packages install
      homebrew:
        name: "{{ item.name }}"
        state: "{{ item.state | default('present') }}"
      with_items: "{{ homebrew_packages }}"

    - name: install prezto
      git: repo=https://github.com/sorin-ionescu/prezto.git dest=~/.zprezto

    - name: install tpm
      git: repo=https://github.com/tmux-plugins/tpm.git dest=~/.tmux/plugins/tpm

  handlers:
    - name: run fc-cache
      shell: fc-cache -vf
